market/applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        '', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'users/register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'users/logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'users/update-password/<pk>/', 
        views.UpdatePasswordView.as_view(),
        name='user-update_password',
    ),
    path(
        'users/update/<pk>/', 
        views.UserUpdateView.as_view(),
        name='user-update',
    ),
    path(
        'users/delete/<pk>/', 
        views.UserDeleteView.as_view(),
        name='user-delete',
    ),
    path(
        'users/lista/', 
        views.UserListView.as_view(),
        name='user-lista',
    ),
]

market/market/urls.py
"""
Proyecto Final
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
]

market/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    # TIPO DE USUARIOS
    ADMINISTRADOR = '0'
    ALMACEN = '1'
    VENTAS = '2'
    # GENEROS
    VARON = 'M'
    MUJER = 'F'
    OTRO = 'O'
    #
    OCUPATION_CHOICES = [
        (ADMINISTRADOR, 'Administrador'),
        (ALMACEN, 'Almacen'),
        (VENTAS, 'Ventas'),
    ]

    GENDER_CHOICES = [
        (VARON, 'Masculino'),
        (MUJER, 'Femenino'),
        (OTRO, 'Otros'),
    ]

    email = models.EmailField(unique=True)
    full_name = models.CharField('Nombres', max_length=100)
    ocupation = models.CharField(
        max_length=1, 
        choices=OCUPATION_CHOICES, 
        blank=True
    )
    genero = models.CharField(
        max_length=1, 
        choices=GENDER_CHOICES, 
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def get_short_name(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

market/applications/users/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña',
                'class': 'input-group-field',
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña',
                'class': 'input-group-field',
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'email',
            'full_name',
            'ocupation',
            'genero',
            'date_birth',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electronico ...',
                    'class': 'input-group-field',
                }
            ),
            'full_name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombres ...',
                    'class': 'input-group-field',
                }
            ),
            'ocupation': forms.Select(
                attrs={
                    'placeholder': 'Ocupacion ...',
                    'class': 'input-group-field',
                }
            ),
            'date_birth': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'type': 'date',
                    'class': 'input-group-field',
                },
            ),
        }
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    email = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'input-group-field',
                'placeholder': 'Correo Electronico',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'input-group-field',
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data


class UserUpdateForm(forms.ModelForm):

    class Meta:

        model = User
        fields = (
            'email',
            'full_name',
            'ocupation',
            'genero',
            'date_birth',
            'is_active',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electronico ...',
                    'class': 'input-group-field',
                }
            ),
            'full_name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombres ...',
                    'class': 'input-group-field',
                }
            ),
            'ocupation': forms.Select(
                attrs={
                    'placeholder': 'Ocupacion ...',
                    'class': 'input-group-field',
                }
            ),
            'date_birth': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'type': 'date',
                    'class': 'input-group-field',
                },
            ),
            'is_active': forms.CheckboxInput(
                attrs={
                },
            ),
        }


class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Actual'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva'
            }
        )
    )

market/applications/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic import (
    View,
    CreateView,
    ListView,
    UpdateView,
    DeleteView
)

from django.views.generic.edit import (
    FormView
)

from .forms import (
    UserRegisterForm, 
    LoginForm,
    UserUpdateForm,
    UpdatePasswordForm,
)
#
from .models import User
# 


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-lista')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name=form.cleaned_data['full_name'],
            ocupation=form.cleaned_data['ocupation'],
            genero=form.cleaned_data['genero'],
            date_birth=form.cleaned_data['date_birth'],
        )
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)



class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:index')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )



class UserUpdateView(UpdateView):
    template_name = "users/update.html"
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('users_app:user-lista')


class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('users_app:user-lista')


class UpdatePasswordView(LoginRequiredMixin, FormView):
    # template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)


class UserListView(ListView):
    template_name = "users/lista.html"
    context_object_name = 'usuarios'

    def get_queryset(self):
        return User.objects.usuarios_sistema()
    

market/templates/users/base_users.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

market/templates/users/lista.html
{% extends "users/base_users.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Usuarios del Sistema</h3>  
  <table class="cell">
      <thead>
          <th>Email</th>
          <th>Nombres</th>
          <th>Ultima Conexion</th>
          <th>Permisos</th>
          <th>Estado</th>
          <th>Acciones</th>
      </thead>
      <tbody>
        {% for usuario in usuarios %}
          <tr>
            <td>{{ usuario.email }}</td>
            <td>{{ usuario.full_name }}</td>
            <td>{{ usuario.last_login }}</td>
            <td>{{ usuario.get_ocupation_display }}</td>
            <td>
              {% if usuario.is_active %}
                <span class="label success">Activo</span>
              {% else %}
                <span class="label alert">De Baja</span>
              {% endif %}
            </td>
            <td>
            <a href="{% url 'users_app:user-update' usuario.pk %}" class="button warning"><i class="fi-pencil"></i></a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
  </table>

  <div class="cell">
    <a href="{% url 'users_app:user-register' %}" class="cell button">Agregar Nuevo Usuario</a>
  </div>
</div>

{% endblock panel-content %}

market/templates/users/login.html
{% extends "base.html" %}

{% load  static %}

{% block content %}

<div class="grid-container">
  <div class="grid-y medium-grid-frame align-center">
    <div class="grid-x grid-padding-x align-center">
      <form class="cell medium-5 grid-x grid-margin-x"
        method="POST" 
        style="border: 1px solid #424242; padding: 2em; border-radius: 10px;"
      >{% csrf_token %}
        <h4 class="cell" style="text-align: center;">Acceso al Sistema</h4>
        <div class="cell medium-12">
          <label>Email:</label>
          <div class="input-group">
            <span class="input-group-label"><i class="fi-mail"></i></span>
            {{form.email}}
          </div>
        </div>
        <div class="cell medium-12">
          <label>Password:</label>
          <div class="input-group">
            <span class="input-group-label"><i class="fi-lock"></i></span>
            {{form.password}}
          </div>
        </div>
        <button type="submit" class="cell warning button">Ingresar</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

market/templates/users/register.html
{% extends "users/base_users.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Datos Nuevo Usuario</h3>  
  <form class="cell medium-9 grid-x grid-margin-x" method="POST">{% csrf_token %}
      
    <div class="cell medium-12">
      <label>Email:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-mail"></i></span>
        {{ form.email }}
      </div>
      {% for error in form.email.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Nombre:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{form.full_name}}
      </div>
    </div>

    <div class="cell medium-6">
      <label>Permisos:</label>
      <div class="input-group">
        {{form.ocupation}}
      </div>
    </div>
    <div class="cell medium-6">
      <label>Genero:</label>
      <div class="input-group">
        {{form.genero}}
      </div>
    </div>

    <div class="cell medium-6">
      <label>Fecha de Nacimiento:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{ form.date_birth }}
      </div>
    </div>
    
    <div class="cell medium-6">
      <label>Contraseña:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-key"></i></span>
        {{ form.password1 }}
      </div>
      {% for error in form.password1.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Repetir Contraseña:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-key"></i></span>
        {{ form.password2 }}
      </div>
      {% for error in form.password2.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>

    <div class="cell medium-8">
      <button type="submit" class="cell success button" style="width: 200px;">Guardar</button>
      {% if object %}
      <a href="#" class="cell alert button clear">Eliminar</a>
      {% endif %}
    </div>
  </form>
</div>

{% endblock panel-content %}

market/templates/users/update.html
{% extends "users/base_users.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Datos Usuario</h3>  
  <form class="cell medium-9 grid-x grid-margin-x align-center" method="POST">{% csrf_token %}
      
    <div class="cell medium-12">
      <label>Email:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-mail"></i></span>
        {{ form.email }}
      </div>
      {% for error in form.email.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Nombre:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{form.full_name}}
      </div>
    </div>

    <div class="cell medium-6">
      <label>Permisos:</label>
      <div class="input-group">
        {{form.ocupation}}
      </div>
    </div>
    <div class="cell medium-6">
      <label>Genero:</label>
      <div class="input-group">
        {{form.genero}}
      </div>
    </div>

    <div class="cell medium-6">
      <label>Fecha de Nacimiento:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{ form.date_birth }}
      </div>
    </div>

    <div class="cell medium-6">
        <label>Usuario Activo:</label>
        <div class="input-group">
          {{ form.is_active }}
        </div>
    </div>

    <div class="cell medium-10">
      <button type="submit" class="cell button success">Guardar</button>
    </div>
  </form>
  <form class="cell medium-5" action="{% url 'users_app:user-delete' object.id %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="cell alert button">Eliminar</button>
  </form>
</div>

{% endblock panel-content %}