market/applications/venta/urls.py
#
from django.urls import path
from . import views

app_name = "venta_app"

urlpatterns = [
    path(
        'venta/index/', 
        views.AddCarView.as_view(),
        name='venta-index',
    ),
    path(
        'carshop/update/<pk>/', 
        views.CarShopUpdateView.as_view(),
        name='carshop-update',
    ),
    path(
        'carshop/delete/<pk>/', 
        views.CarShopDeleteView.as_view(),
        name='carshop-delete',
    ),
    path(
        'carshop/delete-all/', 
        views.CarShopDeleteAll.as_view(),
        name='carshop-delete_all',
    ),
    path(
        'venta/simple/', 
        views.ProcesoVentaSimpleView.as_view(),
        name='venta-simple',
    ),
    path(
        'venta/voucher/', 
        views.ProcesoVentaVoucherView.as_view(),
        name='venta-voucher',
    ),
    path(
        'venta/voucher-pdf/<pk>/', 
        views.VentaVoucherPdf.as_view(),
        name='venta-voucher_pdf',
    ),
    path(
        'venta/ultimas-ventas/', 
        views.SaleListView.as_view(),
        name='venta-list',
    ),
    path(
        'venta/delete/<pk>/', 
        views.SaleDeleteView.as_view(),
        name='venta-delete',
    ),
]

market/market/urls.py
"""
Proyecto Final
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
]

market/applications/venta/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_delete, post_save
#
from model_utils.models import TimeStampedModel

# local apps
from applications.producto.models import Product

#
from .managers import SaleManager, SaleDetailManager, CarShopManager
from .signals import update_stok_ventas_producto


class Sale(TimeStampedModel):
    """Modelo que representa a una Venta Global"""

    # tipo recibo constantes
    BOLETA = '0'
    FACTURA = '1'
    SIN_COMPROBANTE = '2'
    # tipo pago constantes
    TARJETA = '0'
    CASH = '1'
    BONO = '2'
    OTRO = '3'
    #
    TIPO_INVOCE_CHOICES = [
        (BOLETA, 'Boleta'),
        (FACTURA, 'Factura'),
        (SIN_COMPROBANTE, 'Sin Comprobante'),
    ]

    TIPO_PAYMENT_CHOICES = [
        (TARJETA, 'Tarjeta'),
        (CASH, 'Cash'),
        (BONO, 'Bono'),
        (OTRO, 'Otro'),
    ]

    date_sale = models.DateTimeField(
        'Fecha de Venta',
    )
    count = models.PositiveIntegerField('Cantidad de Productos')
    amount = models.DecimalField(
        'Monto', 
        max_digits=10, 
        decimal_places=2
    )
    type_invoce = models.CharField(
        'TIPO',
        max_length=2,
        choices=TIPO_INVOCE_CHOICES
    )
    type_payment = models.CharField(
        'TIPO PAGO',
        max_length=2,
        choices=TIPO_PAYMENT_CHOICES
    )
    close = models.BooleanField(
        'Venta cerrada',
        default=False
    )
    anulate = models.BooleanField(
        'Venta Anulada',
        default=False,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='cajero',
        related_name="user_venta",
    )

    objects = SaleManager()

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'ventas'

    def __str__(self):
        return 'Nº [' + str(self.id) + '] - ' + str(self.date_sale)



class SaleDetail(TimeStampedModel):
    """Modelo que representa a una venta en detalle"""

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_sale'
    )
    sale = models.ForeignKey(
        Sale,
        on_delete=models.CASCADE, 
        verbose_name='Codigo de Venta',
        related_name='detail_sale'
    )
    count = models.PositiveIntegerField('Cantidad')
    price_purchase = models.DecimalField(
        'Precio Compra', 
        max_digits=10, 
        decimal_places=3
    )
    price_sale = models.DecimalField(
        'Precio Venta', 
        max_digits=10, 
        decimal_places=2
    )
    tax = models.DecimalField(
        'Impuesto', 
        max_digits=5,
        decimal_places=2
    )
    anulate = models.BooleanField(default=False)
    #

    objects = SaleDetailManager()

    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return str(self.sale.id) + ' - ' + str(self.product.name)


class CarShop(TimeStampedModel):
    """Modelo que representa a un carrito de compras"""

    barcode = models.CharField(
        max_length=13,
        unique=True
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_car'
    )
    count = models.PositiveIntegerField('Cantidad')
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.name)


# signals for venta
post_save.connect(update_stok_ventas_producto, sender=SaleDetail)

market/applications/venta/forms.py
from django import forms
#local
from .models import Sale


class VentaForm(forms.Form):
    barcode = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'Codigo de barras',
                'class': 'input-group-field',
            }
        )
    )
    count = forms.IntegerField(
        min_value=1,
        widget=forms.NumberInput(
            attrs = {
                'value': '1',
                'class': 'input-group-field',
            }
        )
    )
    #
    def clean_count(self):
        count = self.cleaned_data['count']
        if count < 1:
            raise forms.ValidationError('Ingrese una cantidad mayor a cero')

        return count
    

class VentaVoucherForm(forms.Form):

    type_payment = forms.ChoiceField(
        required=False,
        choices=Sale.TIPO_PAYMENT_CHOICES,
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )
    type_invoce = forms.ChoiceField(
        required=False,
        choices=Sale.TIPO_INVOCE_CHOICES,
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )

market/applications/venta/views.py
# django
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    View,
    UpdateView,
    DeleteView,
    DeleteView,
    ListView
)
from django.views.generic.edit import (
    FormView
)
# local
from applications.producto.models import Product
from applications.utils import render_to_pdf
from applications.users.mixins import VentasPermisoMixin
#
from .models import Sale, SaleDetail, CarShop
from .forms import VentaForm, VentaVoucherForm
from .functions import procesar_venta


class AddCarView(VentasPermisoMixin, FormView):
    template_name = 'venta/index.html'
    form_class = VentaForm
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["productos"] = CarShop.objects.all()
        context["total_cobrar"] = CarShop.objects.total_cobrar()
        # formulario para venta con voucher
        context['form_voucher'] = VentaVoucherForm
        return context
    
    def form_valid(self, form):
        barcode = form.cleaned_data['barcode']
        count = form.cleaned_data['count']
        obj, created = CarShop.objects.get_or_create(
            barcode=barcode,
            defaults={
                'product': Product.objects.get(barcode=barcode),
                'count': count
            }
        )
        #
        if not created:
            obj.count = obj.count + count
            obj.save()
        return super(AddCarView, self).form_valid(form)
    


class CarShopUpdateView(VentasPermisoMixin, View):
    """ quita en 1 la cantidad en un carshop """

    def post(self, request, *args, **kwargs):
        car = CarShop.objects.get(id=self.kwargs['pk'])
        if car.count > 1:
            car.count = car.count - 1
            car.save()
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )


class CarShopDeleteView(VentasPermisoMixin, DeleteView):
    model = CarShop
    success_url = reverse_lazy('venta_app:venta-index')


class CarShopDeleteAll(VentasPermisoMixin, View):
    
    def post(self, request, *args, **kwargs):
        #
        CarShop.objects.all().delete()
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )


class ProcesoVentaSimpleView(VentasPermisoMixin, View):
    """ Procesa una venta simple """

    def post(self, request, *args, **kwargs):
        #
        procesar_venta(
            self=self,
            type_invoce=Sale.SIN_COMPROBANTE,
            type_payment=Sale.CASH,
            user=self.request.user,
        )
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )


class ProcesoVentaVoucherView(VentasPermisoMixin, FormView):
    form_class = VentaVoucherForm
    success_url = '.'
    
    def form_valid(self, form):
        type_payment = form.cleaned_data['type_payment']
        type_invoce = form.cleaned_data['type_invoce']
        #
        venta = procesar_venta(
            self=self,
            type_invoce=type_invoce,
            type_payment=type_payment,
            user=self.request.user,
        )
        #
        if venta: 
            return HttpResponseRedirect(
                reverse(
                    'venta_app:venta-voucher_pdf',
                    kwargs={'pk': venta.pk },
                )
            )
        else:
            return HttpResponseRedirect(
                reverse(
                    'venta_app:venta-index'
                )
            )
                


class VentaVoucherPdf(VentasPermisoMixin, View):
    
    def get(self, request, *args, **kwargs):
        venta = Sale.objects.get(id=self.kwargs['pk'])
        data = {
            'venta': venta,
            'detalle_productos': SaleDetail.objects.filter(sale__id=self.kwargs['pk'])
        }
        pdf = render_to_pdf('venta/voucher.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


class SaleListView(VentasPermisoMixin, ListView):
    template_name = 'venta/ventas.html'
    context_object_name = "ventas" 

    def get_queryset(self):
        return Sale.objects.ventas_no_cerradas()



class SaleDeleteView(VentasPermisoMixin, DeleteView):
    template_name = "venta/delete.html"
    model = Sale
    success_url = reverse_lazy('venta_app:venta-index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.anulate = True
        self.object.save()
        # actualizmos sl stok y ventas
        SaleDetail.objects.restablecer_stok_num_ventas(self.object.id)
        success_url = self.get_success_url()

        return HttpResponseRedirect(success_url)

    

market/templates/venta/base_venta.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

market/templates/venta/delete.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">¿Desea eliminar esta Venta?</h5>  
  <form class="cell medium-9 grid-x grid-margin-x align-center" 
    action="{% url 'venta_app:venta-delete' sale.id %}" method="POST">
    {% csrf_token %}
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-divider">
              <h3>Monto: {{ sale.amount }}</h3>
            </div>
            <div class="card-section">
              <h4>ID: {{ sale.id }}</h4>
              <p>FECHA: {{ sale.date_sale }}</p>
              <p>CANTIDAD PRODUCTOS: {{ sale.count }}</p>
              <p>TIPO DE COMPROBANTE: {{ sale.get_type_invoce_display }}</p>
              <p>TIPO DE PAGO: {{ sale.get_type_payment_display }}</p>
            </div>
        </div>
    </div>
    
    <div class="cell medium-6">
      <button type="submit" class="alert button">Eliminar</button>
      <a href="{% url 'venta_app:venta-index' %}" class="primary button clear">Cancelar</a>
    </div>
  </form>
</div>

{% endblock panel-content %}

market/templates/venta/index.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <div class="cell grid-x grid-margin-x">
    <form class="cell small-7 input-group" method="POST">{% csrf_token %}
      <span class="input-group-label">COD/CAN:</span>
      {{ form.barcode }}
      {{ form.count }}
      <div class="input-group-button">
        <input type="submit" class="button secondary" value="Agregar">
      </div>
    </form>
    <form class="cell small-3" action="{% url 'venta_app:venta-simple' %}" method="POST">{% csrf_token %}
      <button type="submit" class="cell button success">
        <i class="fi-shopping-cart"></i>
        <span>Pagar Todo</span>
      </button>
    </form>
    <div class="cell small-2">
      <a class="cell hollow button secondary" href="{% url 'venta_app:venta-list' %}">
        <i class="fi-trash"></i>
        <span>Ultimas Ventas</span>
      </a>
    </div>
  </div>

  <div class="grid-x grid-margin-x" style="padding: 1.5em;">
    <!-- contendor de la lista de productos en venta -->
    <div class="cell medium-8">
      <h5 class="cell"> Productos en Venta</h5>
      <table class="hover">
        <thead>
          <th width="200">COD</th>
          <th width="250">Nombres</th>
          <th width="120">Precio (S/)</th>
          <th width="100">Cantidad</th>
          <th>Acciones</th>
          <th></th>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
              <td>{{ producto.barcode }}</td>
              <td>{{ producto.product.name }}</td>
              <td>{{ producto.product.sale_price }}</td>
              <td>{{ producto.count }}</td>
              <td>
                <form action="{% url 'venta_app:carshop-update' producto.id %}" method="POST">{% csrf_token %}
                  <button type="submit" class="button primary"><i class="fi-minus"></i></button>
                </form>
              </td>
              <td>
                <form action="{% url 'venta_app:carshop-delete' producto.id %}" method="POST">{% csrf_token %}
                  <button type="submit" class="button alert"><i class="fi-x"></i></button>
                </form>
              </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

    <!-- contiene los resultados resltantes -->
    <div class="cell medium-4">
      <div class="callout success" style="text-align: center;">
        <h5>Total a Cobrar:</h5>
        <h2> S/ {{ total_cobrar }} </h2>
      </div>

      <br>

      <form class="cell" action="{% url 'venta_app:venta-simple' %}" 
        method="POST">{% csrf_token %}
        <button type="submit" class="cell button primery" style="padding: 1.5em;">
          <i class="fi-credit-card"></i>
          <span>Pagar Todo</span>
        </button>
      </form>
      
      <button data-open="exampleModal1" class="cell button success" style="padding: 1.5em;">
        <i class="fi-print"></i>
          <span>Cobrar e Imprimir</span>
      </button>

      <form class="cell" action="{% url 'venta_app:carshop-delete_all' %}" 
        method="POST">{% csrf_token %}
        <button type="submit" class="cell hollow button alert">
          <i class="fi-trash"></i>
          <span>Limpiar Todo</span>
        </button>
      </form>
    </div>

  </div>

  <!-- modal para el cobrar con comprobante de pago -->
  <div class="reveal" id="exampleModal1" data-reveal>
    <h3>Detalle del comprobante de pago</h3>
    <form action="{% url 'venta_app:venta-voucher' %}" class="grid-x grid-margin-x" 
      method="POST">{% csrf_token %}
      <div class="cell medium-6">
        <label>Tipo de Pago:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_voucher.type_payment }}
        </div>
        {% for error in form.type_payment.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Tipo de Comprobante:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-archive"></i></span>
          {{ form_voucher.type_invoce }}
        </div>
        {% for error in form.type_invoce.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>

      <button type="submit" class="cell success button">Pagar</button>
    </form>
  </div>

</div>

{% endblock panel-content %}

market/templates/venta/ventas.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
    <h3 class="cell" style="text-align: center;">Ultimas Ventas Registradas</h3>
    <div class="cell">
        <table>
            <thead>
                <th>Nomero</th>
                <th>Fecha</th>
                <th>Cantidad Productos</th>
                <th>Monto Total</th>
                <th>Anular</th>
            </thead>
            <tbody>
                {% for venta in ventas %}
                <tr>
                  <td>{{venta.id}}</td>
                  <td>{{venta.date_sale}}</td>
                  <td>{{venta.count}}</td>
                  <td>{{venta.amount}}</td>
                  <td>
                    <a href="{% url 'venta_app:venta-delete' venta.id %}" class="button alert"><i class="fi-x"></i></a>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock panel-content %}

market/templates/venta/voucher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Market DJ S.A</h3>
    <table>
        <tr>
            <td>N°</td><td>{{venta.id}}</td>
            <td>Fecha:</td><td>{{venta.date_sale}}</td>
        </tr>
        <tr>
            <td>Cantidad de Productos:</td><td>{{venta.count}}</td>
            <td>Monto Pagado:</td><td>{{venta.amount}}</td>
        </tr>
        <tr>
            <td>Tipo de Pago:</td><td>{{venta.get_type_invoce_display}}</td>
        </tr>
    </table>

    <h4>Poductos comprados:</h4>
    <ul>
        {% for producto in detalle_productos %}
          <li>{{ producto.product.name }} --- {{ producto.count }} --- {{ producto.price_sale}}</li>
        {% endfor %}
    </ul>
</body>
</html>