market/applications/producto/urls.py
#
from django.urls import path
from . import views

app_name = "producto_app"

urlpatterns = [
    path(
        'producto/lista/', 
        views.ProductListView.as_view(),
        name='producto-lista',
    ),
    path(
        'producto/agregar/', 
        views.ProductCreateView.as_view(),
        name='producto-add',
    ),
    path(
        'producto/agregar/<pk>/', 
        views.ProductUpdateView.as_view(),
        name='producto-update',
    ),
    path(
        'producto/eliminar/<pk>/', 
        views.ProductDeleteView.as_view(),
        name='producto-delete',
    ),
    path(
        'producto/detalle/<pk>/', 
        views.ProductDetailView.as_view(),
        name='producto-detail',
    ),
    path(
        'producto/detalle/print/<pk>/', 
        views.ProductDetailViewPdf.as_view(),
        name='producto-detail_print',
    ),
    path(
        'producto/reporte/', 
        views.FiltrosProductListView.as_view(),
        name='producto-filtros',
    ),
]

market/market/urls.py
"""
Proyecto Final
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
]

market/applications/producto/models.py
# third-party
from model_utils.models import TimeStampedModel
# Django
from django.db import models
# local
from .managers import ProductManager

class Marca(TimeStampedModel):
    """
        Marca de un producto
    """

    name = models.CharField(
        'Nombre', 
        max_length=30
    )

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    def __str__(self):
        return self.name


class Provider(TimeStampedModel):
    """
        Proveedore de Producto
    """

    name = models.CharField(
        'Razon Social', 
        max_length=100
    )
    email = models.EmailField(
        blank=True, 
        null=True
    )
    phone = models.CharField(
        'telefonos',
        max_length=40,
        blank=True,
    )
    web = models.URLField(
        'sitio web',
        blank=True,
    )


    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'

    def __str__(self):
        return self.name


class Product(TimeStampedModel):
    """
        Producto
    """

    UNIT_CHOICES = (
        ('0', 'Kilogramos'),
        ('1', 'Litros'),
        ('2', 'Unidades'),
    )

    barcode = models.CharField(
        max_length=13,
        unique=True
    )
    name = models.CharField(
        'Nombre', 
        max_length=40
    )
    provider = models.ForeignKey(
        Provider, 
        on_delete=models.CASCADE
    )
    marca = models.ForeignKey(
        Marca, 
        on_delete=models.CASCADE
    )
    due_date = models.DateField(
        'fehca de vencimiento',
        blank=True, 
        null=True
    )
    description = models.TextField(
        'descripcion del producto',
        blank=True,
    )
    unit = models.CharField(
        'unidad de medida',
        max_length=1,
        choices=UNIT_CHOICES, 
    )
    count = models.PositiveIntegerField(
        'cantidad en almacen',
        default=0
    )
    purchase_price = models.DecimalField(
        'precio compra',
        max_digits=7, 
        decimal_places=2
    )
    sale_price = models.DecimalField(
        'precio venta',
        max_digits=7, 
        decimal_places=2
    )
    num_sale = models.PositiveIntegerField(
        'numero de ventas',
        default=0
    )
    anulate = models.BooleanField(
        'eliminado',
        default=False
    )

    #
    objects = ProductManager()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.name

market/applications/producto/forms.py
# django
from django import forms
# local
from .models import Product


class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = (
            'barcode',
            'name',
            'provider',
            'marca',
            'due_date',
            'description',
            'unit',
            'count',
            'purchase_price',
            'sale_price',
        )
        widgets = {
            'barcode': forms.TextInput(
                attrs = {
                    'placeholder': 'Codigo de barras',
                    'class': 'input-group-field',
                }
            ),
            'name': forms.TextInput(
                attrs = {
                    'placeholder': 'Nombre...',
                    'class': 'input-group-field',
                }
            ),
            'due_date': forms.DateInput(
                format='%Y-%m-%d',
                attrs = {
                    'type': 'date',
                    'class': 'input-group-field',
                }
            ),
            'description': forms.Textarea(
                attrs = {
                    'placeholder': 'Descripcion del producto',
                    'rows': '3',
                    'class': 'input-group-field',
                }
            ),
            'unit': forms.Select(
                attrs = {
                    'class': 'input-group-field',
                }
            ),
            'count': forms.NumberInput(
                attrs = {
                    'placeholder': 'Codigo de barras',
                    'class': 'input-group-field',
                }
            ),
            'purchase_price': forms.NumberInput(
                attrs = {
                    'placeholder': '1',
                    'class': 'input-group-field',
                }
            ),
            'sale_price': forms.NumberInput(
                attrs = {
                    'placeholder': '1',
                    'class': 'input-group-field',
                }
            ),
        }
    # validations
    def clean_barcode(self):
        barcode = self.cleaned_data['barcode']
        if len(barcode) < 11:
            raise forms.ValidationError('Ingrese un codigo de barras correcto')

        return barcode
    
    def clean_purchase_price(self):
        purchase_price = self.cleaned_data['purchase_price']
        if not purchase_price > 0:
            raise forms.ValidationError('Ingrese un precio compra mayor a cero')

        return purchase_price
    
    def clean_sale_price(self):
        sale_price = self.cleaned_data['sale_price']
        purchase_price = self.cleaned_data.get('purchase_price')
        if not sale_price >= purchase_price:
            raise forms.ValidationError('El precio de venta debe ser mayor o igual que el precio de compra')

        return sale_price

market/applications/producto/views.py
# Django
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    View,
)
# local
from applications.venta.models import SaleDetail
from applications.users.mixins import AlmacenPermisoMixin
#
from .models import Product
from .forms import ProductForm
from applications.utils import render_to_pdf


class ProductListView(AlmacenPermisoMixin, ListView):
    template_name = "producto/lista.html"
    context_object_name = 'productos'

    def get_queryset(self):
        kword = self.request.GET.get("kword", '')
        order = self.request.GET.get("order", '')
        queryset = Product.objects.buscar_producto(kword, order)
        return queryset



class ProductCreateView(AlmacenPermisoMixin, CreateView):
    template_name = "producto/form_producto.html"
    form_class = ProductForm
    success_url = reverse_lazy('producto_app:producto-lista')


class ProductUpdateView(AlmacenPermisoMixin, UpdateView):
    template_name = "producto/form_producto.html"
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('producto_app:producto-lista')



class ProductDeleteView(AlmacenPermisoMixin, DeleteView):
    template_name = "producto/delete.html"
    model = Product
    success_url = reverse_lazy('producto_app:producto-lista')


class ProductDetailView(AlmacenPermisoMixin, DetailView):
    template_name = "producto/detail.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #
        context["ventas_mes"] = SaleDetail.objects.ventas_mes_producto(
            self.kwargs['pk']
        )
        return context


class ProductDetailViewPdf(AlmacenPermisoMixin, View):
    
    def get(self, request, *args, **kwargs):
        producto = Product.objects.get(id=self.kwargs['pk'])
        data = {
            'product': producto,
            'ventas_mes': SaleDetail.objects.ventas_mes_producto(self.kwargs['pk'])
        }
        pdf = render_to_pdf('producto/detail-print.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


class FiltrosProductListView(AlmacenPermisoMixin, ListView):
    template_name = "producto/filtros.html"
    context_object_name = 'productos'

    def get_queryset(self):

        queryset = Product.objects.filtrar(
            kword=self.request.GET.get("kword", ''),
            date_start=self.request.GET.get("date_start", ''),
            date_end=self.request.GET.get("date_end", ''),
            provider=self.request.GET.get("provider", ''),
            marca=self.request.GET.get("marca", ''),
            order=self.request.GET.get("order", ''),
        )
        return queryset
    


    

market/templates/producto/base_producto.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

market/templates/producto/delete.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">¿Desea eliminar el producto?</h5>  
  <form class="cell medium-9 grid-x grid-margin-x align-center" 
    action="{% url 'producto_app:producto-delete' product.id %}" method="POST">
    {% csrf_token %}
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-divider">
              Quedan: {{ product.count }}
            </div>
            <div class="card-section">
              <h4>{{ product.name }}</h4>
              <p>Proveedor: {{ product.provider }}</p>
              <p>Descripcion: {{ product.description }}</p>
              <p>Codigo: {{ product.barcode }}</p>
            </div>
        </div>
    </div>
    
    <div class="cell medium-6">
      <button type="submit" class="alert button">Eliminar</button>
      <a href="{% url 'producto_app:producto-lista' %}" class="primary button clear">Volver</a>
    </div>
  </form>
</div>

{% endblock panel-content %}

market/templates/producto/detail-print.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    .table {
      border-collapse: separate;
    }
    .tr {
      border: 2px solid #424242;
      padding: 5px;
    }
  </style>
</head>
<body>
  <h3>{{ product.name }}</h3>
  <div>
    <table>
      <tbody>
        <tr>
          <td>Codigo de Barras:</td><td>{{ product.barcode }}</td>
          <td>Proveedor:</td><td>{{ product.provider }}</td>
        </tr>
        <tr>
          <td>Marca:</td><td>{{ product.marca }}</td>
          <td>Vencimiento:</td><td>{{ product.due_date }}</td>
        </tr>
        <tr>
          <td>Unidad de medida:</td><td>{{ product.get_unit_display }}</td>
          <td>Proveedor:</td><td>{{ product.provider }}</td>
        </tr>
        <tr>
          <td>Cantidad en Almacen:</td><td>{{ product.count }}</td>
          <td>Numero de Ventas:</td><td>{{ product.num_sale }}</td>
        </tr>
        <tr>
          <td>Precio Venta::</td><td>{{ product.sale_price }}</td>
          <td>Precio Compra:</td><td>{{ product.purchase_price }}</td>
        </tr>
        <tr>
          <td>Descripcion:</td><td>{{ product.description }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div>
    <h3>Cantidad de ventas ultimos 30 dias</h3>
  </div>
  <table class="table">
    <thead>
        <th>Fecha</th>
        <th>Producto</th>
        <th>Ventas</th>
    </thead>
    <tbody>
        {% for ventas in ventas_mes %}
        <tr class="tr">
            <td>{{ ventas.sale__date_sale__date }}</td>
            <td>{{ ventas.product__name }}</td>
            <td>{{ ventas.cantidad_vendida }}</td>
        </tr>
        {% empty %}
        <p>No hay ventas para este producto</p>
        {% endfor %}
    </tbody>
  </table>
</body>
</html>

market/templates/producto/detail.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">Detalle del producto</h5>  
  <div class="cell medium-9 grid-x grid-margin-x align-center">
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-section">
              <h4>{{ product.name }}</h4>
              <p><span style="font-weight: bold;">Codigo de Barras:</span> {{ object.barcode }}</p>
              <p><span style="font-weight: bold;">Proveedor:</span> {{ product.provider }}</p>
              <p><span style="font-weight: bold;">Marca:</span> {{ product.marca }}</p>
              <p><span style="font-weight: bold;">Vencimiento:</span> {{ product.due_date }}</p>
              <p><span style="font-weight: bold;">Unidad de medida:</span> {{ product.get_unit_display }}</p>
              <p><span style="font-weight: bold;">Cantidad en Almacen:</span> {{ product.count }}</p>
              <p><span style="font-weight: bold;">Precio Compra:</span> {{ product.purchase_price }}</p>
              <p><span style="font-weight: bold;">Precio Venta:</span> {{ product.sale_price }}</p>
              <p><span style="font-weight: bold;">Numero de Ventas:</span> {{ product.num_sale }}</p>
              <p><span style="font-weight: bold;">Descripcion:</span> {{ product.description }}</p>
            </div>
        </div>
    </div>
    <h4 class="cell">Ventas en los ultimos 30 dias</h4>
    <div class="cell">
        <table class="hover">
            <thead>
                <th>Fecha</th>
                <th>Producto</th>
                <th>Ventas</th>
            </thead>
            <tbody>
                {% for ventas in ventas_mes %}
                <tr>
                    <td>{{ ventas.sale__date_sale__date }}</td>
                    <td>{{ ventas.product__name }}</td>
                    <td>{{ ventas.cantidad_vendida }}</td>
                </tr>
                {% empty %}
                <p style="color: green;">No hay ventas para este producto</p>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="cell medium-6">
      <a target="_blank" href="{% url 'producto_app:producto-detail_print' product.id %}" class="primary button">Imprimir</a>
    </div>
  </div>
</div>

{% endblock panel-content %}

market/templates/producto/filtros.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <form class="cell grid-x grid-margin-x" method="GET">
    <div class="cell input-group">
      <span class="input-group-label">Codigo o Nombre</span>
      <input class="input-group-field" type="text" id="kword" name="kword" 
        value="{{request.GET.kword}}"
        placeholder="Codigo o nombre ..."
        >
    </div>
    <div class="cell grid-x grid-margin-x">
        <p class="cell">Por Fecha de Vencimiento:</p>
        <input type="date" name="date_start" id="date_start" class="cell medium-4">
        <input type="date" name="date_end" id="date_end" class="cell medium-4">
        <p class="cell">Proveedor o Marca:</p>
        <input type="text" name="provide" id="provider" class="cell medium-4" placeholder="Proveedor...">
        <input type="text" name="marca" id="marca" class="cell medium-4" placeholder="Marca...">
        <button class="cell medium-4 button success">Filtrar</button>
    </div>
  </form>

  <div class="cell grid-x grid-margin-x" style="margin-top: 2em;">
    <table class="hover">
      <thead>
        <th>COD</th>
        <th>
          
          {% if request.path == request.get_full_path %}
          <a href="{{request.get_full_path}}?order=name"> Nombres</a>
          {% else %}
          <a href="{{request.get_full_path}}&order=name"> Nombres</a>
          {% endif %}
        </th>
        <th>Precio Venta</th>
        <th>Precio Compra</th>
        <th>
          {% if request.path == request.get_full_path %}
          <a href="{{request.get_full_path}}?order=stok">Stock</a>
          {% else %}
          <a href="{{request.get_full_path}}&order=stok">Stock</a>
          {% endif %}
        </th>
        <th>
          {% if request.path == request.get_full_path %}
          <a href="{{request.get_full_path}}?order=num">Ventas</a>
          {% else %}
          <a href="{{request.get_full_path}}&order=num">Ventas</a>
          {% endif %}
        </th>
        <th>Vencimiento</th>
        <th>Acciones</th>
      </thead>
      <tbody>
        {% for producto in productos %}
          <tr>
            <td>{{producto.barcode}}</td>
            <td>{{producto.name}}</td>
            <td>{{producto.sale_price}}</td>
            <td>{{producto.purchase_price}}</td>
            <td>{{producto.count}}</td>
            <td>{{producto.num_sale}}</td>
            <td>{{producto.due_date}}</td>
            <td>
              <a href="{% url 'producto_app:producto-detail' producto.id %}" class="button warning"><i class="fi-eye"></i></a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock panel-content %}

market/templates/producto/form_producto.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Datos de Producto</h3>  
  <form class="cell medium-9 grid-x grid-margin-x" method="POST">{% csrf_token %}
      
    <div class="cell medium-6">
      <label>Codigo de barras:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-align-justify"></i></span>
        {{ form.barcode }}
      </div>
      {% for error in form.barcode.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Nombre:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{form.name}}
      </div>
    </div>

    <div class="cell medium-6">
      <label>Proveedor:</label>
      <div class="input-group">
        {{form.provider}}
      </div>
    </div>
    <div class="cell medium-6">
      <label>Marca:</label>
      <div class="input-group">
        {{form.marca}}
      </div>
    </div>

    <div class="cell medium-6">
        <label>Unidad de Medida:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-price-tag"></i></span>
          {{ form.unit }}
        </div>
      </div>
    <div class="cell medium-6">
      <label>Fecha de Vencimiento:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{ form.due_date }}
      </div>
    </div>

    <div class="cell medium-6">
        <label>Precio Compra:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-dollar"></i></span>
          {{form.purchase_price}}
        </div>
        {% for error in form.purchase_price.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
    </div>
    <div class="cell medium-6">
        <label>Precio Venta:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-dollar"></i></span>
          {{form.sale_price}}
        </div>
        {% for error in form.sale_price.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
    </div>

    <div class="cell medium-12">
      <label>Cantidad en Almacen:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-list-number"></i></span>
        {{form.count}}
      </div>
    </div>

    <div class="cell medium-12">
        <label>Descripcion del producto:</label>
        <div class="input-group">
          {{form.description}}
        </div>
      </div>
    

    <div class="cell medium-6">
      <button type="submit" class="success button" style="width: 200px;">Guardar</button>
      {% if product %}
      <a href="{% url 'producto_app:producto-delete' product.id %}" class="alert button clear">Eliminar</a>
      {% endif %}
    </div>
  </form>
</div>

{% endblock panel-content %}

market/templates/producto/lista.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <div class="cell grid-x grid-margin-x">
    <form class="cell small-9 input-group" method="GET">
      <span class="input-group-label">COD</span>
      <input class="input-group-field" type="text" id="kword" name="kword" placeholder="nombre o codigo...">
      <div class="input-group-button">
        <input type="submit" class="button secondary" value="Buscar">
      </div>
    </form>
    <div class="cell small-3">
      <a href="{% url 'producto_app:producto-add' %}" class="button success">Registrar Nuevo</a>
    </div>
  </div>


  <div class="cell grid-x grid-margin-x">
    <div class="cell small-2">
      <a href="?order=name">
        <span class="label warning">Por Nombre</span>
      </a>
    </div>
    <div class="cell small-2">
      <a href="?order=date">
        <span class="label secondary">Por Fecha</span>
      </a>
    </div>
    <div class="cell small-2">
      <a href="?order=stok">
        <span class="label">Por Stok</span>
      </a>
    </div>
  </div>

  <div class="cell grid-x grid-margin-x" style="margin-top: 2em;">
    <table class="hover">
      <thead>
        <th>COD</th>
        <th>Nombres</th>
        <th>Precio Venta</th>
        <th>Precio Compra</th>
        <th>Stok</th>
        <th>Num Ventas</th>
        <th>Acciones</th>
      </thead>
      <tbody>
        {% for producto in productos %}
          <tr>
            <td>{{producto.barcode}}</td>
            <td>{{producto.name}}</td>
            <td>{{producto.sale_price}}</td>
            <td>{{producto.purchase_price}}</td>
            <td>{{producto.count}}</td>
            <td>{{producto.num_sale}}</td>
            <td>
              <a href="{% url 'producto_app:producto-update' producto.id %}" class="button"><i class="fi-pencil"></i></a>
              <a href="{% url 'producto_app:producto-detail' producto.id %}" class="button warning"><i class="fi-eye"></i></a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock panel-content %}