market/applications/caja/urls.py
#
from django.urls import path
from . import views

app_name = "caja_app"

urlpatterns = [
    path(
        'cierre-caja/index/', 
        views.ReporteCierreCajaView.as_view(),
        name='caja-index',
    ),
    path(
        'cierre-caja/cerrar/', 
        views.ProcesoCerrarCajaView.as_view(),
        name='caja-cerrar',
    ),
]

market/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'panel/', 
        views.PanelHomeView.as_view(),
        name='index',
    ),
    path(
        'panel/admin/', 
        views.PanelAdminView.as_view(),
        name='index-admin',
    ),
    path(
        'panel/admin-reporte/', 
        views.ReporteAdmin.as_view(),
        name='admin-reporte',
    ),
    path(
        'panel/admin-liquidacion/', 
        views.ReporteLiquidacion.as_view(),
        name='admin-liquidacion',
    ),
    path(
        'panel/admin-resumen-ventas/', 
        views.ReporteResumenVentas.as_view(),
        name='admin-resumen_ventas',
    ),
]

market/applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        '', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'users/register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'users/logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'users/update-password/<pk>/', 
        views.UpdatePasswordView.as_view(),
        name='user-update_password',
    ),
    path(
        'users/update/<pk>/', 
        views.UserUpdateView.as_view(),
        name='user-update',
    ),
    path(
        'users/delete/<pk>/', 
        views.UserDeleteView.as_view(),
        name='user-delete',
    ),
    path(
        'users/lista/', 
        views.UserListView.as_view(),
        name='user-lista',
    ),
]

market/applications/venta/urls.py
#
from django.urls import path
from . import views

app_name = "venta_app"

urlpatterns = [
    path(
        'venta/index/', 
        views.AddCarView.as_view(),
        name='venta-index',
    ),
    path(
        'carshop/update/<pk>/', 
        views.CarShopUpdateView.as_view(),
        name='carshop-update',
    ),
    path(
        'carshop/delete/<pk>/', 
        views.CarShopDeleteView.as_view(),
        name='carshop-delete',
    ),
    path(
        'carshop/delete-all/', 
        views.CarShopDeleteAll.as_view(),
        name='carshop-delete_all',
    ),
    path(
        'venta/simple/', 
        views.ProcesoVentaSimpleView.as_view(),
        name='venta-simple',
    ),
    path(
        'venta/voucher/', 
        views.ProcesoVentaVoucherView.as_view(),
        name='venta-voucher',
    ),
    path(
        'venta/voucher-pdf/<pk>/', 
        views.VentaVoucherPdf.as_view(),
        name='venta-voucher_pdf',
    ),
    path(
        'venta/ultimas-ventas/', 
        views.SaleListView.as_view(),
        name='venta-list',
    ),
    path(
        'venta/delete/<pk>/', 
        views.SaleDeleteView.as_view(),
        name='venta-delete',
    ),
]

market/market/urls.py
"""
Proyecto Final
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
]

market/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-MX">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/foundation-icons/foundation-icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <title>{% block title %}{% endblock title %}</title>
  {% block css %}{% endblock css %}
</head>
<body>

  {% block content %}
  {% endblock content %}

  {% block js %}
  
  {% endblock js %}
</body>
<script src="{% static 'js/vendor/jquery.js' %}"></script>
<script src="{% static 'js/vendor/what-input.js' %}"></script>
<script src="{% static 'js/vendor/foundation.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
</html>

market/templates/panel.html
{% extends "base.html" %}

{% load  static %}

{% block content %}

<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>

    <div class="off-canvas position-left reveal-for-large" id="my-info" data-off-canvas data-position="left" style="background-color: #424242;">
      <div class="row column">
        <h3 style="text-align: center; padding: 0.3em; color: #ffae00;">Market DJ</h3>
        <ul class="vertical menu">
            <li>
              <a href="#"><span class="label warning">Almacen</span></a>
              <ul class="nested vertical menu">
                <li class="{% if request.resolver_match.url_name == 'producto-lista' %}activeli{% endif %}">
                  <a href="{% url 'producto_app:producto-lista' %}" style="color: white;">Productos</a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'producto-filtros' %}activeli{% endif %}">
                  <a href="{% url 'producto_app:producto-filtros' %}" style="color: white;">Reportes</a>
                </li>
              </ul>
            </li>
        </ul>
        <ul class="vertical menu">
            <li>
              <a href="#"><span class="label warning">Ventas</span></a>
              <ul class="nested vertical menu">
                <li class="{% if request.resolver_match.url_name == 'venta-index' %}activeli{% endif %}">
                  <a href="{% url 'venta_app:venta-index' %}" style="color: white;">Vender</a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'caja-index' %}activeli{% endif %}">
                  <a href="{% url 'caja_app:caja-index' %}" style="color: white;">Cerrar Caja</a>
                </li>
              </ul>
            </li>
        </ul>
        <ul class="vertical menu">
            <li>
              <a href="#"><span class="label warning">Administracion</span></a>
              <ul class="nested vertical menu">
                <li class="{% if request.resolver_match.url_name == 'index-admin' %}activeli{% endif %}">
                  <a href="{% url 'home_app:index-admin' %}" style="color: white;">Administracion</a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'user-lista' %}activeli{% endif %}">
                  <a href="{% url 'users_app:user-lista' %}" style="color: white;">Usuarios</a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'admin-reporte' %}activeli{% endif %}">
                  <a href="{% url 'home_app:admin-reporte' %}" style="color: white;">Reportes</a>
                </li>
              </ul>
            </li>
        </ul>
      </div>
    </div>

    <div class="off-canvas-content" data-off-canvas-content>
      <!-- declaramos un nuevo bloque para contenidod e panel -->
      <div class="grid-x">
        <div class="cell top-bar" style="background-color: #424242;">
          <div class="top-bar-left">
            <h4 style="color: white;">Sesion de: {{ user.full_name }}</h4>
          </div>
          <div class="top-bar-right">
            <a href="{% url 'users_app:user-logout' %}">
              <span class="label warning">Salir</span>
            </a>
          </div>
        </div>
      </div>
      <div class="grid-container" style="padding: 1em;">
        {% block panel-content %}
        {% endblock panel-content %}
      </div>
  </div>
</div>
{% endblock content %}